## Model Training

In [39]:
import pandas as pd

In [40]:
df=pd.read_csv('data/gemstone.csv')
df.head()

   id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [41]:
df=df.drop(labels='id',axis=1)
df.head()

   carat        cut color clarity  depth  table     x     y     z  price
0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [42]:
## Dependent and Independent feature
x=df.drop(labels='price',axis=1)
y=df[['price']]

In [43]:
df.head()

   carat        cut color clarity  depth  table     x     y     z  price
0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [44]:
x.head()

   carat        cut color clarity  depth  table     x     y     z
0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77

In [45]:
y.head()

   price
0  13619
1  13387
2   2772
3    666
4  14453

In [46]:
x.head()

   carat        cut color clarity  depth  table     x     y     z
0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77

In [48]:
categorical_cols=x.select_dtypes(include='object').columns
numerical_cols=x.select_dtypes(exclude='object').columns

In [49]:
categorical_cols

Index(['cut', 'color', 'clarity'], dtype='object')

In [50]:
numerical_cols

Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [51]:
cut_categories=['Fair','Good','Very Good','Premium','Ideal']
color_categories=['D','E','F','G','H','I','J']
clarity_categories=['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

In [52]:
y.isnull().sum()

price    0
dtype: int64

In [53]:
from sklearn.impute import SimpleImputer ## Handling missing values like NAN
from sklearn.preprocessing import StandardScaler ## Doing the feature scaling 
from sklearn.preprocessing import OrdinalEncoder ## For Ordinal Encoding
from sklearn.pipeline import Pipeline ## Pipeline
from sklearn.compose import ColumnTransformer

In [54]:
numerical_cols

Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [56]:
## Numerical Pipeline
num_pipeline=Pipeline(steps=[('imputer',SimpleImputer(strategy='median')),
                             ('scaler',StandardScaler())])

## Categorical Pipeline
cat_pipeline=Pipeline(steps=[('imputer',SimpleImputer(strategy='most_frequent')),
                             ('ordinal encoder',OrdinalEncoder(categories=[cut_categories,color_categories,clarity_categories]))])

preprocessor=ColumnTransformer([('num_pipeline',num_pipeline,numerical_cols),
                                ('cat_pipeline',cat_pipeline,categorical_cols)])

In [57]:
preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('ordinal encoder',
                                                  OrdinalEncoder(categories=[['Fair',
                                                                              'Good',
                                                                              'Very '
                                                                              'Good',
                                                                              'Premium',
                                                                              'Ideal'],
                                                                             ['D',
                                                                              'E',
                                                                              'F',
                                                                              'G',
                                                                              'H',
                                                                              'I',
                                                                              'J'],
                                                                             ['I1',
                                                                              'SI2',
                                                                              'SI1',
                                                                              'VS2',
                                                                              'VS1',
                                                                              'VVS2',
                                                                              'VVS1',
                                                                              'IF']]))]),
                                 Index(['cut', 'color', 'clarity'], dtype='object'))])

In [58]:
x

        carat        cut color clarity  depth  table     x     y     z
0        1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1        2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2        0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3        0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4        1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77
...       ...        ...   ...     ...    ...    ...   ...   ...   ...
193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67
193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47
193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62
193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81
193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48

[193573 rows x 9 columns]

In [19]:
y

        price
0       13619
1       13387
2        2772
3         666
4       14453
...       ...
193568   1130
193569   2874
193570   3036
193571    681
193572   2258

[193573 rows x 1 columns]

In [59]:
## Train Test Split

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [60]:
x_train

        carat        cut color clarity  depth  table     x     y     z
11504    0.41      Ideal     E    VVS2   60.6   56.0  4.85  4.80  2.93
95284    1.23  Very Good     H     VS1   59.9   59.0  6.91  7.01  4.19
184777   1.70    Premium     H     VS2   62.0   58.0  7.61  7.66  4.74
5419     0.33      Ideal     F    VVS1   61.2   56.0  4.47  4.44  2.73
45466    0.33  Very Good     I     SI1   62.1   58.0  4.41  4.45  2.75
...       ...        ...   ...     ...    ...    ...   ...   ...   ...
119879   0.50  Very Good     E     SI1   60.2   61.0  5.11  5.15  3.09
103694   1.91  Very Good     F     SI1   62.3   62.0  7.85  7.79  4.87
131932   1.22    Premium     G     VS2   62.8   58.0  6.82  6.74  4.26
146867   0.31  Very Good     G    VVS1   61.1   56.0  4.37  4.40  2.67
121958   0.31  Very Good     G     SI2   61.8   59.0  4.34  4.38  2.70

[135501 rows x 9 columns]

In [22]:
x

        carat        cut color clarity  depth  table     x     y     z
0        1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1        2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2        0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3        0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4        1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77
...       ...        ...   ...     ...    ...    ...   ...   ...   ...
193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67
193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47
193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62
193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81
193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48

[193573 rows x 9 columns]

In [23]:
x_train

        carat        cut color clarity  depth  table     x     y     z
11504    0.41      Ideal     E    VVS2   60.6   56.0  4.85  4.80  2.93
95284    1.23  Very Good     H     VS1   59.9   59.0  6.91  7.01  4.19
184777   1.70    Premium     H     VS2   62.0   58.0  7.61  7.66  4.74
5419     0.33      Ideal     F    VVS1   61.2   56.0  4.47  4.44  2.73
45466    0.33  Very Good     I     SI1   62.1   58.0  4.41  4.45  2.75
...       ...        ...   ...     ...    ...    ...   ...   ...   ...
119879   0.50  Very Good     E     SI1   60.2   61.0  5.11  5.15  3.09
103694   1.91  Very Good     F     SI1   62.3   62.0  7.85  7.79  4.87
131932   1.22    Premium     G     VS2   62.8   58.0  6.82  6.74  4.26
146867   0.31  Very Good     G    VVS1   61.1   56.0  4.37  4.40  2.67
121958   0.31  Very Good     G     SI2   61.8   59.0  4.34  4.38  2.70

[135501 rows x 9 columns]

In [24]:
x_test

        carat        cut color clarity  depth  table     x     y     z
14868    0.50      Ideal     D     SI1   62.1   57.0  5.05  5.08  3.14
165613   2.00  Very Good     G     SI2   59.5   57.0  8.08  8.15  4.89
96727    0.27    Premium     E    VVS1   60.5   59.0  4.19  4.16  2.52
145593   0.32    Premium     I    VVS1   61.2   59.0  4.43  4.44  2.71
118689   1.19      Ideal     H     SI1   62.5   56.0  6.77  6.81  4.23
...       ...        ...   ...     ...    ...    ...   ...   ...   ...
39151    0.91  Very Good     I     SI2   62.4   59.0  6.18  6.13  3.83
32423    0.51      Ideal     D     VS2   62.4   56.0  5.13  5.11  3.19
17876    0.41      Ideal     G    VVS1   61.8   56.0  4.79  4.77  2.95
72938    1.21    Premium     I     SI1   61.1   60.0  6.88  6.79  4.18
2265     1.01  Very Good     E     VS2   62.8   56.0  6.33  6.46  4.02

[58072 rows x 9 columns]

In [61]:
x_train=pd.DataFrame(preprocessor.fit_transform(x_train),columns=preprocessor.get_feature_names_out())
x_test=pd.DataFrame(preprocessor.transform(x_test),columns=preprocessor.get_feature_names_out())

In [63]:
x_train

,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-0.823144,-1.129988,-0.641897,-0.780451,-0.835103,-0.876024,4.0,1.0,5.0
1,0.945023,-1.777823,0.921902,1.073226,1.166389,0.946633,2.0,4.0,4.0
2,1.958484,0.165682,0.400636,1.703116,1.755063,1.742237,3.0,4.0,3.0
3,-0.995648,-0.574701,-0.641897,-1.122391,-1.161138,-1.165334,4.0,2.0,6.0
4,-0.995648,0.258230,0.400636,-1.176382,-1.152082,-1.136403,2.0,5.0,2.0
...,...,...,...,...,...,...,...,...,...
135496,-0.629077,-1.500179,1.964434,-0.546492,-0.518125,-0.644575,2.0,1.0,2.0
135497,2.411307,0.443325,2.485700,1.919078,1.872797,1.930288,2.0,2.0,2.0
135498,0.923460,0.906065,0.400636,0.992240,0.921862,1.047891,3.0,3.0,3.0
135499,-1.038774,-0.667249,-0.641897,-1.212375,-1.197364,-1.252127,2.0,3.0,6.0
135500,-1.038774,-0.019414,0.921902,-1.239371,-1.215477,-1.208731,2.0,3.0,1.0

In [64]:
y_test

        price
14868    1355
165613  14691
96727     844
145593    707
118689   5797
...       ...
39151    2974
32423    1875
17876     967
72938    5656
2265     6759

[58072 rows x 1 columns]

In [ ]:
## Model Training
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [29]:
x_train

,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-0.823144,-1.129988,-0.641897,-0.780451,-0.835103,-0.876024,4.0,1.0,5.0
1,0.945023,-1.777823,0.921902,1.073226,1.166389,0.946633,2.0,4.0,4.0
2,1.958484,0.165682,0.400636,1.703116,1.755063,1.742237,3.0,4.0,3.0
3,-0.995648,-0.574701,-0.641897,-1.122391,-1.161138,-1.165334,4.0,2.0,6.0
4,-0.995648,0.258230,0.400636,-1.176382,-1.152082,-1.136403,2.0,5.0,2.0
...,...,...,...,...,...,...,...,...,...
135496,-0.629077,-1.500179,1.964434,-0.546492,-0.518125,-0.644575,2.0,1.0,2.0
135497,2.411307,0.443325,2.485700,1.919078,1.872797,1.930288,2.0,2.0,2.0
135498,0.923460,0.906065,0.400636,0.992240,0.921862,1.047891,3.0,3.0,3.0
135499,-1.038774,-0.667249,-0.641897,-1.212375,-1.197364,-1.252127,2.0,3.0,6.0
135500,-1.038774,-0.019414,0.921902,-1.239371,-1.215477,-1.208731,2.0,3.0,1.0

In [30]:
x_test

,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-0.629077,0.258230,-0.120630,-0.600482,-0.581521,-0.572248,4.0,0.0,2.0
1,2.605374,-2.148014,-0.120630,2.126042,2.198832,1.959219,2.0,3.0,1.0
2,-1.125026,-1.222536,0.921902,-1.374347,-1.414721,-1.469110,3.0,1.0,6.0
3,-1.017211,-0.574701,0.921902,-1.158385,-1.161138,-1.194265,3.0,5.0,6.0
4,0.858771,0.628421,-0.641897,0.947248,0.985258,1.004495,4.0,4.0,2.0
...,...,...,...,...,...,...,...,...,...
58067,0.255007,0.535873,0.921902,0.416340,0.369414,0.425874,2.0,5.0,1.0
58068,-0.607514,0.535873,-0.641897,-0.528495,-0.554351,-0.499920,4.0,0.0,3.0
58069,-0.823144,-0.019414,-0.641897,-0.834441,-0.862273,-0.847093,4.0,3.0,6.0
58070,0.901897,-0.667249,1.443168,1.046230,0.967145,0.932167,3.0,5.0,2.0
58071,0.470637,0.906065,-0.641897,0.551317,0.668280,0.700719,2.0,1.0,3.0

In [31]:
y_train

        price
11504    1181
95284    7418
184777  12755
5419     1020
45466     445
...       ...
119879   1410
103694  15064
131932   7209
146867    816
121958    408

[135501 rows x 1 columns]

In [32]:
y_test

        price
14868    1355
165613  14691
96727     844
145593    707
118689   5797
...       ...
39151    2974
32423    1875
17876     967
72938    5656
2265     6759

[58072 rows x 1 columns]

In [33]:
regression=LinearRegression()
regression.fit(x_train,y_train)

LinearRegression()

In [34]:
regression.coef_

array([[ 6432.97591819,  -132.34206204,   -70.48787525, -1701.38593925,
         -494.17005097,   -76.32351645,    69.2043578 ,  -286.18088461,
          434.4886456 ]])

In [35]:
regression.intercept_

array([3190.04701])

In [36]:
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [105]:
## Train Multiple Models

models={'LinearRegression':LinearRegression(),
        'Lasso':Lasso(),
        'Ridge':Ridge(),
        'ElasticNet':ElasticNet()}

models_list=[]
r2_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    
    ## Make Predictions
    y_pred=model.predict(x_test)
    
    mae, rmse, r2_square=evaluate_model(y_test,y_pred)
    print(list(models.keys())[i])
    models_list.append(list(models.keys())[i])
    print("Model Training Performance")
    print('MAE:',mae)
    print("RMSE:",rmse)
    print("r2_square:",r2_square*100)
    
    r2_list.append(r2_square*100)
    print('\n')

print(models_list)
print(r2_list)

LinearRegression
Model Training Performance
MAE: 675.0758270067478
RMSE: 1014.6296630375463
r2_square: 93.62906819996047


Lasso
Model Training Performance
MAE: 676.3788803086726
RMSE: 1014.6596067601726
r2_square: 93.62869215688461


Ridge
Model Training Performance
MAE: 675.1087261318746
RMSE: 1014.63433461596
r2_square: 93.62900953347935


ElasticNet
Model Training Performance
MAE: 1051.1722281863017
RMSE: 1513.647930363851
r2_square: 85.82126162411592


['LinearRegression', 'Lasso', 'Ridge', 'ElasticNet']
[93.62906819996047, 93.62869215688461, 93.62900953347935, 85.82126162411592]

In [106]:
models_list

['LinearRegression', 'Lasso', 'Ridge', 'ElasticNet']